from enum import Enum


class OutcomeType(Enum):
    HEADS_WON = 1
    HEADS_LOSS = 2
    WEATHER_SWELTERING_HEAT = 3
    WEATHER_VERY_SUNNY = 4
    WEATHER_NICE = 5
    WEATHER_POURING_RAIN = 6
    WEATHER_BLIZZARD = 7
    PLAYER_PLACED = 9
    ILLEGAL_SETUP_NUM = 10
    ILLEGAL_SETUP_SCRIMMAGE = 11
    ILLEGAL_SETUP_WINGS = 12
    BALL_PLACED = 13
    KICKOFF_GET_THE_REF = 14
    KICKOFF_RIOT = 15
    KICKOFF_PERFECT_DEFENSE = 16
    KICKOFF_HIGH_KICK = 17
    KICKOFF_CHEERING_FANS = 18
    KICKOFF_CHANGING_WHEATHER = 19
    KICKOFF_BRILLIANT_COACHING = 20
    KICKOFF_QUICK_SNAP = 21
    KICKOFF_BLITZ = 22
    KICKOFF_THROW_A_ROCK = 23
    KICKOFF_PITCH_INVASION = 24
    GET_THE_REF = 25
    RIOT = 26
    HIGH_KICK = 27
    CHEERING_FANS = 28
    BRILLIANT_COACHING = 29
    THROW_A_ROCK = 30
    PITCH_INVASION = 31
    PITCH_INVASION_ROLL = 32
    NOTHING = 33
    KICK_IN_BOUNDS = 34
    KICK_OUT_OF_BOUNDS = 35
    BALL_HIT_GROUND = 36
    BALL_HIT_PLAYER = 37
    SETUP_DONE = 38
    KNOCKED_DOWN = 39
    ARMOR_BROKEN = 40
    ARMOR_NOT_BROKEN = 41
    STUNNED = 42
    KNOCKED_OUT = 43
    BADLY_HURT = 44
    INTERCEPTION = 46
    BALL_CAUGhT = 47
    BALL_DROPPED = 48
    FAILED_DODGE = 49
    SUCCESSFUL_DODGE = 50
    FAILED_GFI = 51
    SUCCESSFUL_GFI = 52
    FAILED_PICKUP = 53
    SUCCESSFUL_PICKUP = 54
    COMPLETE_PASS = 55
    INCOMPLETE_PASS = 56
    COMPLETE_HANDOFF = 57
    INCOMPLETE_HANDOFF = 58
    STUNNED_TURNED = 59
    END_PLAYER_TURN = 60
    MOVE_ACTION_STARTED = 61
    BLOCK_ACTION_STARTED = 62
    BLITZ_ACTION_STARTED = 63
    PASS_ACTION_STARTED = 64
    FOUL_ACTION_STARTED = 65
    HANDOFF_ACTION_STARTED = 66
    END_OF_GAME = 67
    END_OF_PREGAME = 68
    END_OF_TURN = 69
    END_OF_HALF = 70
    TOUCHDOWN = 71
    TURNOVER = 72


class Outcome:

    def __init__(self, outcome_type, pos=None, player_id=-1, opp_player_id=-1, rolls=[], team_home=None, n=0):
        self.outcome_type = outcome_type
        self.pos = pos
        self.player_id = player_id
        self.opp_player_id = opp_player_id
        self.rolls = rolls
        self.team_home = team_home
        self.n = n
